import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { createLecture, createSection, deleteCourse, deleteLecture, deleteSection, getLectures, getMyCourses, getSections } from '../api/instructorApi';

export default function InstructorCourseManager() {
  const { courseId } = useParams();
  const navigate = useNavigate();
  const [course, setCourse] = useState(null); const [sections, setSections] = useState([]); const [lectures, setLectures] = useState({});
  const [sectionTitle, setSectionTitle] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);

  const load = async () => { try { const [coursesRes, sectionsRes] = await Promise.all([getMyCourses(), getSections(courseId)]); const found = (coursesRes.data || []).find((c) => String(c.id) === String(courseId)); setCourse(found); setSections(sectionsRes.data || []); const entries = await Promise.all((sectionsRes.data || []).map(async (s) => [s.id, (await getLectures(s.id)).data || []])); setLectures(Object.fromEntries(entries)); } catch { setError('Unable to load course content.'); } };
  useEffect(() => { load(); }, [courseId]);

  const addSection = async (e) => { e.preventDefault(); if (!sectionTitle.trim()) return; setBusy(true); try { await createSection(courseId, { title: sectionTitle.trim(), description: '', displayOrder: sections.length + 1 }); setSectionTitle(''); await load(); } catch (err) { setError(err.response?.data?.message || 'Unable to create section.'); } finally { setBusy(false); } };
  const removeSection = async (id) => { if (!window.confirm('Delete this section?')) return; try { await deleteSection(courseId, id); await load(); } catch { setError('Unable to delete section.'); } };
  const addLecture = async (section) => { const title = window.prompt('Lecture title'); const videoUrl = window.prompt('Video URL'); if (!title || !videoUrl) return; try { await createLecture(section.id, { title, description: '', videoUrl, durationSeconds: 0, displayOrder: (lectures[section.id]?.length || 0) + 1, preview: false }); await load(); } catch { setError('Unable to create lecture.'); } };
  const removeLecture = async (sectionId, lectureId) => { if (!window.confirm('Delete this lecture?')) return; try { await deleteLecture(sectionId, lectureId); await load(); } catch { setError('Unable to delete lecture.'); } };
  const removeCourse = async () => { if (!window.confirm('Delete this course?')) return; try { await deleteCourse(courseId); navigate('/instructor/dashboard'); } catch { setError('Unable to delete course.'); } };

  if (!course) return <main className="app-shell"><section className="content">{error ? <div className="alert error">{error}</div> : 'Loading...'}</section></main>;
  return <main className="app-shell"><header className="topbar"><strong>E-Learning</strong><div className="actions"><Link className="btn secondary" to={`/instructor/courses/${courseId}/edit`}>Edit</Link><button className="btn danger" onClick={removeCourse}>Delete</button></div></header><section className="content narrow"><div className="page-heading"><div><p className="eyebrow">Course content</p><h1>{course.title}</h1><p className="muted">Status: <b>{course.status}</b> · {course.category}</p></div></div>{error && <div className="alert error">{error}</div>}<form className="inline-form" onSubmit={addSection}><input placeholder="New section title" value={sectionTitle} onChange={(e) => setSectionTitle(e.target.value)} /><button className="btn" disabled={busy}>Add section</button></form><div className="content-list">{sections.map((section) => <article className="manager-card" key={section.id}><div className="manager-head"><div><h2>{section.displayOrder}. {section.title}</h2><p className="muted">{section.description || 'No description'}</p></div><div className="actions"><button className="btn secondary" onClick={() => addLecture(section)}>+ Lecture</button><button className="link-button danger-text" onClick={() => removeSection(section.id)}>Delete</button></div></div><div className="lecture-list">{(lectures[section.id] || []).map((lecture) => <div className="lecture-row" key={lecture.id}><span><b>{lecture.displayOrder}. {lecture.title}</b><small>{lecture.durationSeconds}s · {lecture.preview ? 'Preview' : 'Full'}</small></span><button className="link-button danger-text" onClick={() => removeLecture(section.id, lecture.id)}>Delete</button></div>)}{(lectures[section.id] || []).length === 0 && <p className="muted">No lectures yet.</p>}</div></article>)}</div></section></main>;
}
